
app:
  name: bundles-cloud-migration
  dir: ${user.home}/.bundles-cloud-migration
  db-name: newbundles
  db-host: localhost
  db-port: 5432
  db-url-prefix: jdbc:postgresql://
  db-username: postgres
  db-password: postgres
  csv-dir: ${app.dir}
  countries-filename: bundles_public_countries.csv
  languages-filename: bundles_public_languages.csv
  language-locales-filename: bundles_public_language_locales.csv
  bundle-applications-filename: bundles_public_bundle_applications.csv
  basenames-filename: bundles_public_basenames.csv
  bundlenames-filename: bundles_public_bundlenames.csv
  properties-keys-filename: bundles_public_properties_keys.csv
  properties-values-filename: bundles_public_properties_values.csv
  resourcebundles-filename: bundles_public_resourcebundles.csv

spring:
  main:
    web-application-type: none
  batch:
    initialize-schema: always
  datasource:
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: ${app.db-url-prefix}${app.db-host}:${app.db-port}/${app.db-name}
    jdbcUrl: ${spring.datasource.url}
    username: ${app.db-username}
    password: ${app.db-password}
  jpa:
    hibernate:
      ddl-auto: create-drop
      format_sql: true
      generate_statistics: false
      jdbc:
        batch_size: 5
        batch_versioned_data: true
      show_sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
